### ISSUE TITLE
作者没有提供编译好的文件？

### ISSUE THREAD

**Issue by luohc2004** [15125505/SaveKeyboard#1]
我的破键盘的backspace也有这个毛病...每次按都担心他多删掉我的字符..为了告诉卖家，还录了很久的视频演示.。。。最终是寄回去返修。我不想寄了，先试试你的软件。很好奇剔除多余连击的代码是什么逻辑...我用软件测试了一下，连击和自己快速按的区别不是那么大

**Comment by 15125505** [comment]
当然是有的呀，在release中可以找到，如果你懒得找，下面是链接：
[https://github.com/15125505/SaveKeyboard/releases](https://github.com/15125505/SaveKeyboard/releases)
