### ISSUE TITLE
感谢！

### ISSUE THREAD

**Issue by ghost** [15125505/SaveKeyboard#2]
拯救了我躺了好几年的cherry mx6.0.
感谢！

![image](https://user-images.githubusercontent.com/4153664/64667044-eee3e980-d48a-11e9-97e5-90bef911a577.png)

**Comment by 15125505** [comment]
很高兴能够帮助到别人，我自己都没想到还有别人用^_^

**Comment by MaxwellYe0815** [comment]
> 很高兴能够帮助到别人，我自己都没想到还有别人用^_^

很好的软件，爱来自中国2022
